ALTER TABLE staff 
ADD COLUMN IF NOT EXISTS staff_code VARCHAR(255) 
DEFAULT (CONCAT(
    'STAFF-',
    UPPER(SUBSTRING(MD5(UUID()),1,8))
));
ALTER TABLE staff 
ADD COLUMN IF NOT EXISTS code_status VARCHAR(255) 
DEFAULT "Inactive";
ALTER TABLE event_orders 
ADD COLUMN IF NOT EXISTS referral_code VARCHAR(255) 
DEFAULT '';

ALTER TABLE admin 
ADD COLUMN IF NOT EXISTS staff_code VARCHAR(255) 
DEFAULT (CONCAT(
    'ADMIN-',
    UPPER(SUBSTRING(MD5(UUID()),1,8))
));
ALTER TABLE admin 
ADD COLUMN IF NOT EXISTS code_status VARCHAR(255) 
DEFAULT "Inactive";
ALTER TABLE bank_accounts
ADD COLUMN IF NOT EXISTS service_type VARCHAR(255) NOT NULL DEFAULT "";

ALTER TABLE event_orders
ADD COLUMN IF NOT EXISTS referral_code VARCHAR(255) NOT NULL DEFAULT "";